package com.offnetpay.app.presentation.ui.components

import android.media.AudioAttributes
import android.media.MediaPlayer
import android.view.HapticFeedbackConstants
import androidx.compose.animation.core.LinearOutSlowInEasing
import androidx.compose.animation.core.Spring
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.spring
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalView
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.dp
import com.offnetpay.app.R
import kotlinx.coroutines.delay
import kotlin.math.roundToInt
import kotlin.random.Random

/**
 * Silly-cat easter egg.
 *
 * Triggered from the Settings → About OffNetPay header tap. Pops the
 * `cat_meme.png` photo at a randomly chosen position somewhere on the
 * screen with a spring scale-in animation, holds for a few seconds, then
 * fades out. Tapping anywhere dismisses early.
 *
 * The image source ships in `res/drawable/cat_meme.png` and is generated
 * by `scripts/pack_assets.py` from `artifacts/cat_meme.png`. If the
 * drawable isn't present (artifact missing) the overlay simply finishes
 * silently — never crashes, just does nothing visible.
 *
 * Position is randomised on every invocation: 12-65% from the left edge,
 * 14-58% from the top, so it lands anywhere in the upper two-thirds of
 * the screen and doesn't always pop in the same spot. Size is fixed at
 * 220dp so it reads as a real cat photo regardless of where it lands.
 */
@Composable
fun CatLickingOverlay(onDone: () -> Unit) {
    val view = LocalView.current
    val context = LocalContext.current
    val onDoneState = rememberUpdatedState(onDone)
    val configuration = LocalConfiguration.current

    val screenWidthDp = configuration.screenWidthDp
    val screenHeightDp = configuration.screenHeightDp

    // Resolve the drawable id reflectively so a missing artifact doesn't
    // hard-fail compilation. `R.drawable.cat_meme` is generated by the
    // resource compiler the moment pack_assets.py drops the image in.
    val resId = remember {
        runCatching {
            R.drawable::class.java.getField("cat_meme").getInt(null)
        }.getOrNull() ?: 0
    }

    // Resolve the "bleh" sound id reflectively as well — kept optional so
    // the build doesn't break before the raw resource is dropped in. Place
    // an mp3/wav at `res/raw/bleh.(mp3|wav|m4a|ogg)` and the egg picks it
    // up automatically. We try a couple of common file names so any of
    // them works.
    val soundResId = remember {
        listOf("bleh", "bleh_sound", "cat_bleh").firstNotNullOfOrNull { name ->
            runCatching {
                R.raw::class.java.getField(name).getInt(null)
            }.getOrNull()
        } ?: 0
    }

    if (resId == 0) {
        // No image bundled — fade through immediately so the host's
        // AnimatedVisibility wrapper unmounts us cleanly.
        LaunchedEffect(Unit) { onDoneState.value() }
        return
    }

    val catSizeDp = 220
    // Random landing position. Bounded so the cat stays fully on screen
    // and lands in the upper / mid area (not behind the bottom nav).
    val placement = remember {
        val maxX = (screenWidthDp - catSizeDp).coerceAtLeast(0)
        val maxY = ((screenHeightDp * 0.65f).roundToInt() - catSizeDp).coerceAtLeast(0)
        val x = if (maxX > 0) Random.nextInt(0, maxX) else 0
        val y = if (maxY > 0) Random.nextInt((screenHeightDp * 0.10f).roundToInt(), maxY) else 0
        IntOffset(x, y)
    }

    // Random rotation (-12° → +12°) so the cat looks like it's been
    // tossed onto the screen, not anchored.
    val tilt = remember { Random.nextFloat() * 24f - 12f }

    var dismissing by remember { mutableStateOf(false) }
    val visibility by animateFloatAsState(
        targetValue = if (dismissing) 0f else 1f,
        animationSpec = if (dismissing) {
            tween(durationMillis = 280, easing = LinearOutSlowInEasing)
        } else {
            spring(
                dampingRatio = Spring.DampingRatioMediumBouncy,
                stiffness = Spring.StiffnessLow
            )
        },
        label = "cat_visibility"
    )

    LaunchedEffect(Unit) {
        view.performHapticFeedback(HapticFeedbackConstants.CONFIRM)
        delay(2_400)
        dismissing = true
        delay(320)
        onDoneState.value()
    }

    // Play the bleh sound. Tied to the composable's lifetime via
    // DisposableEffect so the player is released when the overlay
    // dismisses — even if the user backs out early. Volume is fixed-low
    // (0.85) so the egg doesn't blow out the user's ears at full media
    // volume. Whole block silently no-ops if no raw resource is bundled.
    if (soundResId != 0) {
        DisposableEffect(soundResId) {
            val player = runCatching {
                MediaPlayer.create(context, soundResId)?.apply {
                    setAudioAttributes(
                        AudioAttributes.Builder()
                            .setUsage(AudioAttributes.USAGE_GAME)
                            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                            .build()
                    )
                    setVolume(0.85f, 0.85f)
                    setOnCompletionListener { mp ->
                        runCatching { mp.release() }
                    }
                    start()
                }
            }.getOrNull()
            onDispose {
                runCatching { player?.stop() }
                runCatching { player?.release() }
            }
        }
    }

    Box(
        Modifier
            .fillMaxSize()
            // Tap-anywhere to dismiss early. Transparent backdrop so the
            // page underneath stays interactive-looking; the click here
            // is purely to escape the egg sooner.
            .clickable(
                interactionSource = remember { androidx.compose.foundation.interaction.MutableInteractionSource() },
                indication = null
            ) { dismissing = true }
            .background(Color.Black.copy(alpha = 0.18f * visibility))
    ) {
        Image(
            painter = painterResource(id = resId),
            contentDescription = null,
            contentScale = ContentScale.Fit,
            modifier = Modifier
                .offset { placement }
                .size(catSizeDp.dp)
                .graphicsLayer {
                    scaleX = visibility
                    scaleY = visibility
                    rotationZ = tilt
                    alpha = visibility
                }
        )
    }
}
